apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: movlib-evlist
  name: movlib-evlist-rt
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-movlib-evlist
    weight: 100