apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: movlib-evlist
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: movlib-pipe-bind
    template:
      ref: movlib-trigger