resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:17295ec414b809327dc9ba1bdf40e60675be5788bf720019515aae5832595878
  name: quay.io/gtavares_pessoal/movie-library-app
