resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:4fa5d87f973a5964fae43d226fb18fe1547cf95618b47906ee24a072c9af0803
  name: quay.io/gtavares_pessoal/movie-library-app
