resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:dd8a5011eb70cb6c8a23e8b724fa7714587f415f39154ffd4a00bd673359c5ef
  name: quay.io/gtavares_pessoal/movie-library-app
