resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:edf435fc28a4773957dc72f2d58fe56a484adbffdb6a6d91534b6d0841fa19b9
  name: quay.io/gtavares_pessoal/movie-library-app
