resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:a431e04ffcfe5de8772654d48c79c86cb9c7e6a1f50b5b48dae6410dab8c976e
  name: quay.io/gtavares_pessoal/movie-library-app
