resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:51eb632316e86f1392d3daba38c0b2ccf4d31f67bc82b91fb0b4c0d2e0d6505e
  name: quay.io/gtavares_pessoal/movie-library-app
