resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:a298f29e7bab68f7b2e585b45dabd25787f433dd56306366864daee21c2e97a0
  name: quay.io/gtavares_pessoal/movie-library-app
