resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:4916d9cb9b279ff58e9fcf94acdf9bf71e8b1f7874bc701a82baa9ff3337220f
  name: quay.io/gtavares_pessoal/movie-library-app
