resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:dbb2ba758711fc06a7c5cadac496338298a344bc9cd969beb699485f46100e9b
  name: quay.io/gtavares_pessoal/movie-library-app
