resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:2e46fbe6bbfc1414c25f95aacccd206008bb14cb1c74f442d6e0b19f51595544
  name: quay.io/gtavares_pessoal/movie-library-app
